// Create a custom Cloud9 runner - similar to the Sublime build system
// For more information see http://docs.aws.amazon.com/console/cloud9/create-run-config
{
    
    "script":[
        "source /etc/profile.d/maven.sh",
        "mvn clean compile exec:exec"
    ],
    "info" : "Started $project_path$file_name",
    "env" : {},
    "selector" : "source.ext",
    "debugger": "",
    "debugport": "",
    "working_dir": "$project_path/training-developing-in-aws"
}